//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCPSRevenueManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCPSRevenueTable
    {
        public int ID { get; set; }
        public string Quarter1 { get; set; }
        public string Quarter2 { get; set; }
        public string Quarter3 { get; set; }
        public string Quarter4 { get; set; }
        public string Quarter5 { get; set; }
    }
}
