//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityYearJaxDashboard.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Attendance_ID { get; set; }
        public int Enrollment_ID { get; set; }
        public int Dosage_ID { get; set; }
        public int Prevention_ID { get; set; }
        public int Growth_ID { get; set; }
        public int Recovery_ID { get; set; }
    }
}
