//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityYearJaxDashboard.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public int Dashboard_ID { get; set; }
        public int ServiceDelivery_ID { get; set; }
        public int CorpsMemberExp_ID { get; set; }
        public int ExternalAffairs_ID { get; set; }
        public int Revenue_ID { get; set; }
        public int OperationsExpense_ID { get; set; }
        public int RAD_ID { get; set; }
    }
}
