//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityYearJaxDashboard.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int Enrollment_ID { get; set; }
        public Nullable<int> AnnualGoal { get; set; }
        public Nullable<int> BestofCYGoal { get; set; }
        public Nullable<int> Q1Goal { get; set; }
        public Nullable<int> Q1Actual { get; set; }
        public Nullable<int> Q2Goal { get; set; }
        public Nullable<int> Q2Actual { get; set; }
        public Nullable<int> Q3Goal { get; set; }
        public Nullable<int> Q3Actual { get; set; }
        public Nullable<int> Q4Goal { get; set; }
        public Nullable<int> Q4Actual { get; set; }
    }
}
