//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityYearJaxDashboard.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDelivery
    {
        public int ServiceDelivery_ID { get; set; }
        public int ELA_ID { get; set; }
        public int Math_ID { get; set; }
        public int Attendance_ID { get; set; }
        public int Behavior_ID { get; set; }
    }
}
